/NaI/detector1/dimensions -30 0 -20
/NaI/detector1/angle 0
/NaI/detector2/dimensions -15 0 20
/NaI/detector2/angle 180
/NaI/detector3/dimensions 15 0 -20
/NaI/detector3/angle 0
/NaI/detector4/dimensions 30 0 20
/NaI/detector4/angle 180
/pipe/box/activate true
/pipe/box/dim 50 10 10 cm 
/run/numberOfThreads 100 
/run/initialize 
/gps/particle gamma 
/gps/energy 662 keV 
/gps/pos/type Point 
/gps/ang/type iso 
/gps/pos/centre -0.4045 -0.0095 -0.0681 m
/run/beamOn 1000000 
