/NaI/detector1/dimensions -40 0 -20
/NaI/detector1/angle 0
/NaI/detector2/dimensions -20 0 -20
/NaI/detector2/angle 0
/NaI/detector3/dimensions 20 0 20
/NaI/detector3/angle 180
/NaI/detector4/dimensions 40 0 20
/NaI/detector4/angle 180
/pipe/box/activate true
/pipe/box/dim 50 10 10 cm 
/run/numberOfThreads 100 
/run/initialize 
/gps/particle gamma 
/gps/energy 662 keV 
/gps/pos/type Point 
/gps/ang/type iso 
/gps/pos/centre 0.0829 0.0395 -0.0634 m
/run/beamOn 1000000 
