/NaI/detector1/dimensions -40 20 0 cm
/NaI/detector1/angle 90 deg
/NaI/detector2/dimensions -40 -20 0 cm
/NaI/detector2/angle 90 deg
/NaI/detector3/dimensions 40 20 0 cm
/NaI/detector3/angle 90 deg
/NaI/detector4/dimensions 40 -20 0 cm
/NaI/detector4/angle 90 deg
/pipe/box/activate true
/pipe/box/dim 50 10 10 cm
/run/numberOfThreads 6
/run/initialize 
/gps/particle gamma
/gps/energy 662 keV
/gps/pos/centre 0 0 0 cm
/gps/ang/type iso
/run/beamOn 1000000
