/NaI/detector1/dimensions -55 0 0
/NaI/detector1/angle 270
/NaI/detector2/dimensions 0 0 20
/NaI/detector2/angle 180
/NaI/detector3/dimensions 0 0 -20
/NaI/detector3/angle 0
/NaI/detector4/dimensions 55 0 0
/NaI/detector4/angle 90
/pipe/box/activate true
/pipe/box/dim 50 10 10 cm 
/run/numberOfThreads 100 
/run/initialize 
/gps/particle gamma 
/gps/energy 662 keV 
/gps/pos/type Point 
/gps/ang/type iso 
/gps/pos/centre -0.4347 -0.0597 0.0415 m
/run/beamOn 1000000 
